--------------------------------------------------------
--  File created - Monday-November-18-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE_INFO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYEE_INFO" 
   (	"EMP_NO" VARCHAR2(20 BYTE), 
	"EMP_NAME" VARCHAR2(20 BYTE), 
	"DOB" DATE, 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"DOJ" DATE, 
	"MOBILE_NO" VARCHAR2(20 BYTE), 
	"DERP_NO" VARCHAR2(20 BYTE), 
	"SALARY" NUMBER(10,0), 
	"DESIGNATION" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT_INFO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DEPARTMENT_INFO" 
   (	"DEPT_NO" VARCHAR2(20 BYTE), 
	"DEPT_NAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007158
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007158" ON "SYSTEM"."EMPLOYEE_INFO" ("EMP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007162
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007162" ON "SYSTEM"."DEPARTMENT_INFO" ("DEPT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE_INFO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYEE_INFO" MODIFY ("DESIGNATION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYEE_INFO" ADD PRIMARY KEY ("EMP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."EMPLOYEE_INFO" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYEE_INFO" MODIFY ("DERP_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYEE_INFO" MODIFY ("MOBILE_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYEE_INFO" MODIFY ("DOJ" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYEE_INFO" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYEE_INFO" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYEE_INFO" MODIFY ("EMP_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EMPLOYEE_INFO" MODIFY ("EMP_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT_INFO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DEPARTMENT_INFO" ADD PRIMARY KEY ("DEPT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."DEPARTMENT_INFO" MODIFY ("DEPT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."DEPARTMENT_INFO" MODIFY ("DEPT_NO" NOT NULL ENABLE);
